# Generated by Django 3.0.9 on 2021-02-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainDir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periods',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='periods',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='periods',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Период наименование'),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=300, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('snils', models.CharField(max_length=100, verbose_name='СНИЛС')),
                ('contract_date', models.DateField(verbose_name='Дата контракта')),
                ('contract_number', models.CharField(max_length=300, verbose_name='Номер контракта')),
                ('keySchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='mainDir.Periods', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Студенты',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
