# Generated by Django 3.0.9 on 2021-02-20 07:56

from django.db import migrations, models
import django.db.models.deletion
import mainDir.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainDir', '0002_auto_20210220_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='keySchool',
            field=models.ForeignKey(default=mainDir.models.number_school, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='mainDir.Periods', verbose_name='Школа'),
        ),
    ]
