# Generated by Django 3.0.9 on 2021-03-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainDir', '0003_auto_20210220_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='keySchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='mainDir.Periods', verbose_name='Школа'),
        ),
    ]
