# Generated by Django 3.0.9 on 2021-02-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Период')),
                ('date', models.DateField(null=True, verbose_name='Дата обучения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Период обучения',
                'verbose_name_plural': 'Периоды обучения',
            },
        ),
    ]
