# Generated by Django 3.0.9 on 2021-02-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_period_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='is_active',
            field=models.CharField(choices=[('1', 'Активный'), ('0', 'В архив')], default=1, max_length=1, verbose_name='Активный?'),
            preserve_default=False,
        ),
    ]
