# Generated by Django 3.0.9 on 2021-02-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('m', 'Мужской'), ('w', 'Женский')], default='', max_length=1, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
