# Generated by Django 3.0.9 on 2021-02-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_students_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='snils',
            field=models.CharField(default=1, max_length=100, verbose_name='СНИЛС'),
            preserve_default=False,
        ),
    ]
